- name: My first play
  hosts: virtualmachines

#  vars_prompt:
#   - name: email
#     prompt: Whats is your email
#     private: no


  tasks:
   - name: config csaa vars
     ansible.builtin.lineinfile:
       dest: "~/.bashrc"
       state: present
       regexp: "^{{ item.key }}="
       line: "export {{ item.key }}={{ item.value }}"
     with_items: "{{ os_environment }}"
         
   - name: Reset ssh connection to allow user changes to affect
     ansible.builtin.meta: reset_connection

   - name: Turn off Auto-Logout
     ansible.builtin.shell: |
       sed -i -e 's/TMOUT=[[:digit:]]\+/TMOUT=/g' /etc/profile
       sed -i -e 's/TMOUT=[[:digit:]]\+/TMOUT=/g' /etc/bashrc
     become: yes

   - name: Reset ssh connection to allow user changes to affect
     ansible.builtin.meta: reset_connection

   - name: Change file/folder default permissions
     ansible.builtin.shell: |
       sed -i -e 's/umask \+[[:digit:]]\+/umask 022/g' /etc/profile
       sed -i -e 's/umask \+[[:digit:]]\+/umask 022/g' /etc/bashrc
     become: yes

   - name: Reset ssh connection to allow user changes to affect
     ansible.builtin.meta: reset_connection

   - name: Generate ssh config file
     command: touch ~/.ssh/config

   - name: ssh configuration
     ansible.builtin.blockinfile:
       path: ~/.ssh/config
       block: |
         Host github.com
         Hostname ssh.github.com
         Port 443
         User git

   - name: Enabled SSH X11/TCP Forwarding
     ansible.builtin.shell: |
       sed -i -e 's/AllowTcpForwarding no/AllowTcpForwarding yes/g' /etc/ssh/sshd_config
       sed -i -e 's/X11Forwarding no/X11Forwarding yes/g' /etc/ssh/sshd_config
       sh -c 'echo "Compression yes" >> /etc/ssh/sshd_config'
       systemctl reload sshd
     become: yes

   - name: Enable ipv6/4 forwarding
     ansible.builtin.shell: |
       sed -i -e 's/ipv6\.disable=1/ipv6\.disable=0/g' /etc/default/grub
       grub2-mkconfig -o /boot/grub2/grub.cfg
       sed -i -e 's/net\.ipv4\.ip_forward=0/net\.ipv4\.ip_forward=1/g' /etc/sysctl.conf
       sh -c 'echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf'
     become: yes

   - name: Unconditionally reboot the machine with all defaults
     ansible.builtin.reboot:
     become: yes

   - name: Install the git package
     ansible.builtin.package:
       name:
         - git
       state: present
     become: yes

   - name: git configuration
     ansible.builtin.blockinfile:
       path: ~/.ssh/config
       block: |
        [core]
            pager = delta
        [interactive]
            diffFilter = delta --color-only
        [delta]
            navigate = true
            side-by-side = true
        [merge]
            conflictstyle = diff3
        [diff]
            colorMoved = default
        [user]
                name = {{ name }}
                email = {{ email }}
        [alias]
                ls = log --color --graph --pretty=format:\"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset\" --abbrev-commit
                co = checkout
                br = branch
                ci = commit
                st = status
                ll = log --pretty=format:\"%C(yellow)%h%Cred%d %Creset%s%Cblue [%cn]\" --decorate --numstat
        [pull]
                rebase = merges
        [rebase]
                autostash = true
        [status]
                showUntrackedFiles = no

#  - name: Unconditionally reboot the machine with all defaults
#     ansible.builtin.reboot:

#   - name: config csaa vars
#     ansible.builtin.shell:
#       cmd: |
#        cat <<EOF >> ~/.bashrc
#
#        # CSAA Environment Variables
#        export CSAA_EMAIL="{{ email }}"
#        export CSAA_NAME="<NAME>"
#        export CSAA_GITHUB_TOKEN="<GITHUB_TOKEN>"
#        EOF

#   - name: Print env vars
#     command: echo "hello"
#     register: out
#   - debug: var=out.stdout_lines