- name: My first play
  hosts: virtualmachines

#  vars_prompt:
#   - name: email
#     prompt: Whats is your email
#     private: no


  tasks:
   - name: config csaa vars
     ansible.builtin.shell:
       cmd: |
        cat <<EOF >> ~/.bashrc

        # CSAA Environment Variables
        export CSAA_EMAIL="{{ email }}"
        export CSAA_NAME="<NAME>"
        export CSAA_GITHUB_TOKEN="<GITHUB_TOKEN>"
        EOF

   - name: Print to stdout
     command: cat ~/.bashrc
     register: out

   - debug: var=out.stdout_lines

   - name: Reset ssh connection to allow user changes to affect
     ansible.builtin.meta: reset_connection

   - name: Print to stdout
     command: echo "hello"
     register: out

   - debug: var=out.stdout_lines

#  - name: Unconditionally reboot the machine with all defaults
#     ansible.builtin.reboot:

  vars:
    email: ze@uol.com