- name: My first play
  hosts: virtualmachines

#  vars_prompt:
#   - name: email
#     prompt: Whats is your email
#     private: no


  tasks:
   - name: config csaa vars
     ansible.builtin.shell:
       cmd: |
        cat <<EOF >> ~/.bashrc

        # CSAA Environment Variables
        export CSAA_EMAIL="{{ email }}"
        export CSAA_NAME="<NAME>"
        export CSAA_GITHUB_TOKEN="<GITHUB_TOKEN>"
        EOF

   - name: Unconditionally reboot the machine with all defaults
     ansible.builtin.reboot:

  vars:
    email: ze@uol.com